"""Report generation tools — PDF, AI-generated, and listing."""

from __future__ import annotations

from typing import Optional

from sheetstorm_bridge.client import SheetStormAPIError
from sheetstorm_bridge.server import get_client, mcp
from sheetstorm_bridge.tools import artifacts as _artifacts


class LocalPathError(Exception):
    """Never raised by the bridge (it runs on your machine and any local path is allowed)."""


def _safe_local_path(path_str: str):
    return _artifacts._local_path(path_str)


def _write_local_file(path, content: bytes, private: bool = False) -> None:
    _artifacts._write_local_file(path, content)


def _format_report(r: dict) -> str:
    parts = [
        f"**{r.get('title', r.get('report_type', 'Report'))}** (ID: {r.get('id', 'N/A')})",
        f"  Type: {r.get('report_type', 'N/A')} | Format: {r.get('format', 'N/A')}",
        f"  Created: {r.get('created_at', 'N/A')}",
    ]
    if r.get("sha256"):
        size = f" | Size: {r['size_bytes']} bytes" if r.get("size_bytes") is not None else ""
        parts.append(f"  Snapshot: yes (immutable) | SHA-256: {r['sha256']}{size}")
    elif "is_snapshot" in r:
        parts.append("  Snapshot: no (legacy report, re-rendered on download)")
    if r.get("ai_provider"):
        parts.append(f"  AI Provider: {r['ai_provider']}")
    if r.get("generator"):
        gen = r["generator"]
        parts.append(f"  Generated by: {gen.get('name', gen.get('id', 'N/A'))}")
    return "\n".join(parts)


@mcp.tool()
async def sheetstorm_list_reports(incident_id: str) -> str:
    """List generated reports for an incident.

    Args:
        incident_id: UUID of the incident
    """
    client = get_client()
    try:
        data = await client.get(f"/incidents/{incident_id}/reports")
        items = data if isinstance(data, list) else data.get("items", data.get("reports", []))

        if not items:
            return "No reports found for this incident."

        lines = [f"**Reports** ({len(items)})\n"]
        for r in items:
            lines.append(_format_report(r))
            lines.append("")
        return "\n".join(lines)
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"


@mcp.tool()
async def sheetstorm_generate_pdf_report(
    incident_id: str,
    report_type: str = "full",
    sections: Optional[str] = None,
    save_path: Optional[str] = None,
) -> str:
    """Generate (issue) a PDF report for an incident.

    The PDF is stored on the server as an immutable snapshot with its SHA-256;
    later downloads return the same bytes. If the incident's TLP forbids the
    configured AI providers the report is data-only.

    save_path is any local path on your machine.

    Args:
        incident_id: UUID of the incident
        report_type: Report type — one of: executive, full, metrics, ioc, trends
        sections: Optional comma-separated sections to include (defaults to the report type's sections)
        save_path: Optional file to save the PDF to (otherwise only its id and SHA-256 are returned)
    """
    client = get_client()
    try:
        target = None
        if save_path:
            try:
                target = _safe_local_path(save_path)
            except LocalPathError as exc:
                return f"✗ {exc}"
        payload: dict = {"report_type": report_type}
        if sections:
            payload["sections"] = [s.strip() for s in sections.split(",")]

        resp = await client._send("POST", f"/incidents/{incident_id}/reports/generate-pdf", json=payload)
        if "pdf" not in resp.headers.get("content-type", "").lower():
            # Older servers answered with the report record as JSON.
            return f"✓ PDF report generated:\n{_format_report(resp.json())}"

        digest = resp.headers.get("X-Report-SHA256", "")
        lines = [f"✓ PDF report generated ({len(resp.content)} bytes)"]
        if resp.headers.get("X-Report-Id"):
            lines.append(f"  Report ID: {resp.headers['X-Report-Id']}")
        if digest:
            lines.append(f"  SHA-256: {digest}")
        if resp.headers.get("X-SheetStorm-AI-Status"):
            lines.append(f"  AI: not used ({resp.headers['X-SheetStorm-AI-Status']}); data-only report")
        if target is not None:
            try:
                _write_local_file(target, resp.content, private=False)
            except LocalPathError as exc:
                return f"✗ {exc}"
            except OSError as exc:
                return f"✗ Cannot write {save_path}: {exc.strerror or exc}"
            lines.append(f"  Saved to {save_path}")
        else:
            lines.append("  Pass save_path to save the PDF; it is stored on the server and listed by sheetstorm_list_reports.")
        return "\n".join(lines)
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"


@mcp.tool()
async def sheetstorm_generate_ai_report(
    incident_id: str,
    summary_type: str = "executive",
    provider: Optional[str] = None,
) -> str:
    """Generate an AI-written summary of the incident from its timeline, hosts,
    accounts and IOCs using the backend AI service (returned as text, not stored).

    Args:
        incident_id: UUID of the incident
        summary_type: One of: executive, technical, recommendations
        provider: Optional AI provider name configured on the server (default: first available)
    """
    client = get_client()
    try:
        payload: dict = {"summary_type": summary_type}
        if provider:
            payload["provider"] = provider

        result = await client.post(f"/incidents/{incident_id}/reports/ai-generate", json=payload)
        summary = result.get("summary") if isinstance(result, dict) else None
        if not summary:
            return "✗ The AI service returned no summary."
        used = result.get("provider")
        header = f"✓ AI {result.get('summary_type', summary_type)} summary"
        if used:
            header += f" (provider: {used})"
        return f"{header}:\n\n{summary}"
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"
